#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    adduser --quiet --system --group --no-create-home --home /run/bird2 bird2
    dpkg-statoverride --list /etc/bird2 > /dev/null || dpkg-statoverride --update --add bird2 bird2 0750 /etc/bird2
fi

#DEBHELPER#

exit 0
